#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Image-AnimatedGif
version:      0.02
version_from: AnimatedGif.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
