#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Image-AnimatedGif
version:      0.05
version_from: AnimatedGif.pm
installdirs:  site
requires:
    GD:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
